name: Welcome!
description: It's a blog with a bunch of ML stuffs
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://whtstq2.github.io'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://whtstq2.github.io'
author:         'Alissia Park'
